services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - "8001:8001"
    volumes:
      - ./migrations/versions:/fastapi-url-shortener/migrations/versions
    depends_on:
      pg:
        condition: service_healthy  
        
  pg_url_shortener:
    image: postgres:17.7-bookworm
    environment:
      POSTGRES_DB: short_urls
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
      PGPORT: 5433
    ports:
     - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # - ./pg_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d short_urls" ]
      interval: 5s
      timeout: 3s
      retries: 3
volumes:
  pgdata: